from openerp.osv import osv, fields
from openerp import tools

class logs_reportableadverse(osv.Model):
    _name = "logs.reportableadverse"
    _columns = {
        'visitdate' : fields.date('Visit Date'),
        'partner_id': fields.many2one('res.partner', 'Sceening ID'),
        'sceening_id': fields.char(string="Sceening ID", related='partner_id.name'),
        'adverse': fields.text('1. Adverse event: Record diagnosis if available.'),
        'onset' : fields.date('2. Onset date'),
        'reported':fields.date('3. Reported at visit'),
        'grade1':fields.boolean('Grade 1 Mild'),
        'grade2':fields.boolean('Grade 2 Moderate'),
        'grade3':fields.boolean('Grade 3 Severe'),
        'grade4':fields.boolean('Grade 4----Potentially life-threatening'),
        'death1':fields.boolean('Death'),
        'definitely':fields.boolean('Definitely related'),
        'probablyrelated':fields.boolean('Probably related'),
        'possibly':fields.boolean('Possibly related'),
        'probablynot':fields.boolean('Probably not related'),
        'Pending':fields.boolean('Pending'),
        'notrelated':fields.text('Not related, reason'),
        'notapplicable':fields.boolean('Not applicable'),
        'temporarily':fields.boolean('Temporarily withheld'),
        'permanently':fields.boolean('Permanently discontinued'),
        'continuing':fields.boolean('Continued'),
        'continuingat':fields.boolean('Continuing at end of study participation'),
        'resolved' : fields.date('Resolved'),
        'death2' : fields.date('Death'),
        'severity' : fields.date('Severity increased'),
        'none':fields.boolean('None / N/A'),
        'procedure':fields.boolean('Procedure/surgery'),
        'prolongedhospitalization':fields.boolean('New/prolonged hospitalization'),
        'medication':fields.boolean('Medication'),
        'others':fields.boolean('Others: Specify'),
        'SAE':fields.boolean('SAE'),
        'AE':fields.boolean('AE related to PrEP'),
        'death3':fields.boolean('Death'),
        'hospitalization':fields.boolean('Hospitalization'),
        'disability':fields.boolean('Disability'),
        'lifethreatening':fields.boolean('Life threatening / Grade 4'),
        'intervention':fields.boolean('Intervention to prevent above'),
        'congenital':fields.boolean('Congenital anomaly'),
        } 
