from openerp.osv import osv, fields
from openerp import tools

class logs_partnerconcomitant(osv.Model):
    _name = "logs.partnerconcomitant"
    _columns = {
        'visitdate' : fields.date('Visit Date'),
        'partner_id': fields.many2one('res.partner', 'Sceening ID'),
        'sceening_id': fields.char(string="Sceening ID", related='partner_id.name'),
        'medication' : fields.char('1. Medication (generic name):'),
        'indication' : fields.char('Indication:'),
        'startdate' : fields.date('Start date'),
        'stopdate' : fields.date('Stop date'),
        'po':fields.boolean('PO'),
        'im':fields.boolean('IM'),
        'iv':fields.boolean('IV'),
        'top':fields.boolean('TOP'),
        'ihl':fields.boolean('IHL'),
        'others' : fields.char('Others: specify'),
        'dose' : fields.char('Dose/units'),
        'prn':fields.boolean('prn'),
        'qd':fields.boolean('qd'),
        'tid':fields.boolean('tid'),
        'qhs':fields.boolean('qhs'),
        'once':fields.boolean('once'),
        'bd':fields.boolean('bd'),
        'bid':fields.boolean('bid'),
        'qid':fields.boolean('qid'),
        'qod':fields.boolean('qod'),
        'qxh':fields.char('qxh(each hours)'),
        'othersspecify' : fields.char('Others: specify'),
        'Initial' : fields.char('Initials'),
        'medication2' : fields.char('2. Medication (generic name):'),
        'indication2' : fields.char('Indication:'),
        'startdate2' : fields.date('Start date'),
        'stopdate2' : fields.date('Stop date'),
        'po2':fields.boolean('PO'),
        'im2':fields.boolean('IM'),
        'iv2':fields.boolean('IV'),
        'top2':fields.boolean('TOP'),
        'ihl2':fields.boolean('IHL'),
        'others2' :fields.char('Others: specify'),
        'units':fields.char('Dose/units'),
        'prn2':fields.boolean('prn'),
        'qd2':fields.boolean('qd'),
        'tid2':fields.boolean('tid'),
        'qhs2':fields.boolean('qhs'),
        'once2':fields.boolean('once'),
        'bd2':fields.boolean('bd'),
        'bid2':fields.boolean('bid'),
        'qid2':fields.boolean('qid'),
        'qdo2':fields.boolean('qod'),
        'qxh2':fields.char('qxh(each _______hours)'),
        'othersspecify2' : fields.char('Others: specify'),
        'Initial2' : fields.char('Initials'),
        'medication3' : fields.char('3. Medication (generic name):'),
        'indication3' : fields.char('Indication:'),
        'startdate3' : fields.date('Start date'),
        'stopdate3' : fields.date('Stop date'),
        'po3':fields.boolean('PO'),
        'im3':fields.boolean('IM'),
        'iv3':fields.boolean('IV'),
        'top3':fields.boolean('TOP'),
        'ihl3':fields.boolean('IHL'),
        'others3' : fields.char('Others: specify'),
        'dose3' : fields.char('Dose/units'),
        'prn3':fields.boolean('prn'),
        'qd3':fields.boolean('qd'),
        'tid3':fields.boolean('tid'),
        'qhs3':fields.boolean('qhs'),
        'once3':fields.boolean('once'),
        'bd3':fields.boolean('bd'),
        'bid3':fields.boolean('bid'),
        'qid3':fields.boolean('qid'),
        'qod3':fields.boolean('qod'),
        'qxh3':fields.char('qxh(each _______hours)'),
        'othersspecify3' : fields.char('Others: specify'),
        'Initial3' : fields.char('Initials'),
        
        } 
