from openerp.osv import osv, fields
from openerp import tools

class followup_partner_prevention_preference_questionnaire(osv.Model):
    _name = "followuppartner.preventionpreferencequestionnaire"
    _columns = {
    'visit_date':fields.date('Visit Date'),
    'partner_id': fields.many2one('res.partner', 'Sceening ID'),
    'sceening_id': fields.char(string="Screening ID", related='partner_id.name'),
    'noconcerns':fields.boolean('i.	no concerns'),
    'sideeffect':fields.boolean('ii	side effects'),
    'concerns':fields.boolean('iii. concerns about stigma'),
    'notwillling':fields.boolean('iv. not willing to take if there is no benefit for me'),
    'pillburden':fields.boolean("v. pill burden would be too great for too long"),
    'resistance':fields.boolean("vi. resistance may come sooner other"),
    'iwilldie':fields.boolean("vii. taking ARVs means I will die soon"),
    'forcedtodis':fields.boolean("viii. I may be forced to disclose"),
    'others':fields.char("ix. Others:"),
    'starton':fields.boolean("start on ARVs"),
    'partnerprep':fields.boolean("have my partner use PrEP"),
    'both_arvs_and_prep':fields.boolean("Both ARVs and PrEP"),
    'benefitpart':fields.boolean("i. ARVs will benefit my partner in the long term"),
    'arvfree':fields.boolean("ii. ARVs are currently free"),
    'partarv':fields.boolean("iii. My partner is  already using  ARVs"),
    'usedtodrug':fields.boolean("iv. my partner is already used to taking study drug every day"),
    'givehiv':fields.boolean("v. My partner should do everything possible to keep from giving me HIV"),
    'studydrug':fields.boolean("vi. I am already used to taking study drug every day"),
    'showsupport':fields.boolean("vii. I can take PrEP to show support for my partner"),
    'bettrforpart':fields.boolean("viii. better for my partner to be in charge of my own HIVprevention"),
    'trustpartner':fields.boolean("ix. I don\'t trust my partner"),
    'other':fields.boolean("x. Other"),
    'howmanychild':fields.integer("4. How many more children would you like to have now or in the future?(If > 0, go to item 6)"),
    'tryingtogetpreg':fields.boolean("i. currently trying to get pregnant"),
    'currentpregnant':fields.boolean("ii. currently pregnant/partner pregnant"),
    'next2yrs':fields.boolean("iii. within the next 2 years"),
    'morethan2yrs':fields.boolean("iv. More than 2 years from now"),
    'dontknow':fields.boolean("v. Don\'t know"),
    'timedsex':fields.boolean("i. timed unprotected sex"),
    'takeart':fields.boolean("ii. take ART"),
    'prepforpart':fields.boolean("iii. PrEP for my partner"),
    'others':fields.char("Others"),
    'discussed':fields.selection([('1','Yes'),('2','No'),('3','no current partner')],'6. Have you discussed your fertility desires with your current partner?'),
    'highrisk':fields.boolean("i. High risk"),
    "moderaterisk":fields.boolean('ii. Moderate risk'),
    'lowrisk':fields.boolean('iii. Low risk'),
    'donno':fields.boolean('iv Don\'t know'),
    'norisk':fields.boolean('v. No risk'),
    } 
