from openerp.osv import osv, fields
from openerp import tools

class followup_partner_physical_examination(osv.Model):
    _name = "followuppartner.physicalexamination"
    _columns = {
        'visitdate': fields.date('Visit Date'),
        'partner_id': fields.many2one('res.partner', 'Sceening ID'),
        'sceening_id': fields.char(string="Sceening ID", related='partner_id.name'),
        'height': fields.char('Height (Enrollment only)'),
        'weight': fields.char('Weight'),
        'temperature': fields.char('Temperature'),
        'bloodpressure': fields.char('Blood Pressure'),
        'resprate': fields.char('Respiratory Rate'),
        'pulserate': fields.char('Pulse Rate'),
        'gud': fields.selection([('yes','Yes'),('no','No'),('notdone','Not done')],'Genital ulcer disease (GUD)'),
        "vaginitis": fields.selection([('yes','Yes'),('no','No'),('notdone','Not done')],'Vaginitis or vaginal discharge'),
        'cervicitis' : fields.selection([('yes','Yes'),('no','No'),('notdone','Not done')],'Cervicitis or cervical discharge'),
        'pelvic': fields.selection([('yes','Yes'),('no','No'),('notdone','Not done')],'Pelvic inflammatory disease (PID)'),
        'urethritis': fields.selection([('yes','Yes'),('no','No'),('notdone','Not done')],'Urethritis or urethral discharge'),
        "fullycircum":fields.boolean("Fully circumcised"),
        "partiallycircum":fields.boolean("Partially circumcised"),
        "notcircum":fields.boolean("Not circumcised"),
        'treatforgen': fields.selection([('yes','Yes'),('no','No')],'Treatment given for a genital tract infection'),
        'list': fields.char('List medications:'),
        'gingivitis': fields.boolean('gingivitis/periodontitis'),
        'thrush': fields.boolean('Thrush'),
        'ulcer': fields.boolean('Ulcer'),
        'oralhair': fields.boolean('oral hairy leukoplakia'),
        'kaposi': fields.boolean('Kaposi Sarcoma'),
        'others': fields.char('Others'),
        'tenderness':fields.selection([('yes','Yes'),('no','No')],'Abdominal tenderness'),
        'hepatomegaly':fields.selection([('yes','Yes'),('no','No')],'Hepatomegaly'),
        'splenomegaly':fields.selection([('yes','Yes'),('no','No')],'Splenomegaly'),
        'jaundice':fields.selection([('yes','Yes'),('no','No')],'jaundice'),
        'peripheral':fields.selection([('yes','Yes'),('no','No')],'Peripheral edema'),
        'othersigns':fields.selection([('yes','Yes'),('no','No')],'Other physical signs'),
        'specifysigns':fields.selection([('yes','Yes'),('no','No')],'Specify other signs'),
        'zoster':fields.boolean('Zoster'),
        'urticaria':fields.boolean('urticaria'),
        'macular':fields.boolean('diffuse macular, maculopapular, or morbilliform rash'),
        'lesions':fields.boolean('target lesions'),
        'others_2':fields.boolean('Others'),
        'lymphenlarg':fields.selection([('yes','Yes'),('no','No')],'Lymph node enlargement?'),
        'cervical': fields.boolean('Cervical'),
        'inguinal': fields.boolean('Inguinal'),
        'auxillary': fields.boolean('Auxillary'),
        'other_3':fields.char('Others (specify)'),
        'lymphnode': fields.char('Size of largest lymph node'),
    
    } 
