from openerp.osv import osv, fields
from openerp import tools

class followup_sociodemographic(osv.Model):
    _name = "followup.sociodemographic"
    _columns = {
    'visit_date':fields.date('Visit Date'),
    'partner_id': fields.many2one('res.partner', 'Sceening ID'),
    'sceening_id': fields.char(string="Sceening ID", related='partner_id.name'),
    'movedresidence':fields.char('1. How many times has the participant moved primary residence in the past months?'),
    'owntv':fields.selection([('yes','Yes'),('yes','No')],'2. Does the participant own a television?'),
	'ownacell':fields.selection([('yes','Yes'),('yes','No')], '3. Does the participant own a cell phone?'),
	'noincome':fields.boolean('i. no income'),
	'laborer':fields.boolean('ii. laborer/semi-skilled'), 		
	'trade':fields.boolean('iii.	trade/sales'),
	'student':fields.boolean('iv. Student'),
	'profession':fields.boolean('v. Professional'),	
	'farming':fields.boolean('vi. farming/animal raising'),
	'housewife':fields.boolean('vii. housewife (female only)'),
	'otherspecify':fields.boolean('viii. other:'),
	'lessthan30':fields.boolean('i.	less than 30 minutes'),		
	'thirty':fields.boolean('ii. 30-60 minutes'),		
	'onetotwo':fields.boolean('iii.	1-2 hours'),
	'morethan2':fields.boolean('iv.	more than 2 hours'),
	'walk':fields.boolean('Walk'),		
	'bus':fields.boolean('Bus'),		
	'taxi':fields.boolean('Taxi'), 	
	'bicycle':fields.boolean('Bicycle'),
	'perbike':fields.boolean('Personal bike'),		
	'percar':fields.boolean('Personal car'),	
	'amount':fields.char('7	How much did the participant pay for transport to the facility? (Amount)'),
	'losetime':fields.selection([('yes','Yes'),('no','No')],'8. Does the participant or family members lose time at work and/or wages for a typical clinic visit related to taking study drug?'),
	'disclose':fields.selection([('yes','Yes'),('no','No')],'9. Has the participant or the participant\'s study partner disclosed their HIV discordant status to anyone else? (if no end of form)'),
	'children':fields.boolean('i. Children'),	
	'partner':fields.boolean('ii. partner'),
	'indpartpar':fields.boolean('iii. index participant\'s parent(s)'),		
	'commleader':fields.boolean('iv. community leader(s)'),	
	'otherfam':fields.boolean('v. other family members'),	
	'partparfrnd':fields.boolean('vi. participant\'s parent(s) friend(s)'),			
	'pastor':fields.boolean('vii. pastor or other religious leader'),	
	'other':fields.boolean('viii. other, specify:'),	
	'noadvers':fields.boolean('i. no adverse effects'),
	'maritaldis':fields.boolean('ii	marital discord'),
	'lossofhous':fields.boolean('iii. loss of housing'),
	'famdiscord':fields.boolean('iv. family discord'),
	'lossofjob':fields.boolean('v. loss of job/income'),
	'physiviol':fields.boolean('vi. physical violence'),
	'otherspec':fields.boolean('vii. other, specify:'),
	} 
