from openerp.osv import osv, fields
from openerp import tools

class seroconverter_followupmedicalhistory(osv.Model):
    _name = "seroconverter.followupmedicalhistory"
    _columns = {
        'visitdate' : fields.date('Visit Date'),
        'partner_id': fields.many2one('res.partner', 'Sceening ID'),
        'sceening_id': fields.char(string="Sceening ID", related='partner_id.name'),
        'stage1' : fields.selection([('yes','YES'),('no','NO')],'a. Stage 1'),
        'stage2' : fields.selection([('yes','YES'),('no','NO')],'b. Stage 2'),
        'stage3' : fields.selection([('yes','YES'),('no','NO')],'c. Stage 3'),
        'stage4' : fields.selection([('yes','YES'),('no','NO')],'d. Stage 4'),
        'participant' : fields.selection([('yes','YES'),('no','NO')],'2. Is the participant followed in an HIV care program?'),
        'toosick' : fields.selection([('yes','YES'),('no','NO(If no go to 4)')],'3. In the last month, has the participant been too sick to work or do daily activities?'),
        'daysmissed' : fields.integer('a. Number of days missed'),
        'bednet' : fields.selection([('yes','YES'),('no','NO')],'4. In the past week, has the participant used a bednet?'),
        'fortreatment' : fields.selection([('yes','YES'),('no','NO(If no go to 5d)')],'5a. For treatment?'),
        'PMTCT' : fields.selection([('yes','YES'),('no','NO(If no go to 5d)')],'5b. for PMTCT?'),
        'wasstarted' : fields.date('5c. Date when ARV was started'),
        'thengo' : fields.text('5d. List ARVs taken, then go to item 6'),
        'eligible' : fields.boolean('not eligible for ARVs'),
        'count' : fields.boolean('repeat CD4 count > 350 or clinic said wasnt eligible'),
        'stigma' : fields.boolean('Stigma'),
        'adherence' : fields.boolean('adherence was too difficult'),
        'healthy' : fields.boolean('Feeling healthy'),
        'processing' : fields.boolean('pre-treatment processing(in queue at ART center)'),
        'badside' : fields.boolean('fears / has experienced bad side effects'),
        'supportive' : fields.boolean('clinic was not supportive'),
        'clinic' : fields.boolean('no ART slots at the clinic'),
        'transportation' : fields.boolean('transportation costs'),
        'newly' : fields.boolean('Newly diagnosed'),
        'others' : fields.char('Others'),
        'cotrimoxazole' : fields.selection([('yes','YES'),('no','NO')],'6. Is the participant currently taking cotrimoxazole?'),
        'prophylaxis' : fields.boolean('prophylaxis'),
        'toxoplasmosis' : fields.boolean('toxoplasmosis treatment'),
        'PCP' : fields.boolean('PCP treatment'),
        'others2' : fields.char('Others(specify)'),
        'isoniazid' : fields.selection([('yes','YES'),('no','NO')],'7. Is the participant currently taking isoniazid or another medication as prophylaxis for TB?'),
        'treated' : fields.selection([('yes','YES(for how long)'),('no','NO')],'8. Is the participant currently being treated for TB?'),
        'yyyyy' : fields.integer('8a. yyyyy'),
        'currentlypregnant' : fields.selection([('yes','YES(If yes complete pregnancy report)'),('no','NO')],'9. Female only: Is the participant currently pregnant?'),
        'circumcised' : fields.selection([('yes','YES(If yes complete pregnancy report)'),('no','NO')],'10. Male only: Since the last visit, has the participant been circumcised?'),
    }