from openerp.osv import osv, fields
from openerp import tools

class followup_indexmedical(osv.Model):
    _name = "followup.indexmedical"
    _columns = {
    'visitdate' : fields.date('Visit Date'),
    'partner_id': fields.many2one('res.partner', 'Sceening ID'),
    'sceening_id': fields.char(string="Sceening ID", related='partner_id.name'),
    'stage_1':fields.selection([('yes','Yes'),('no','No'),('ineligible','Ineligible')],'a. Stage 1'),
    'stage_2':fields.selection([('yes','Yes'),('no','No'),('ineligible','Ineligible')],'b. Stage 2'),
    'stage_3':fields.selection([('yes','Yes'),('no','No'),('ineligible','Ineligible')],'c. Stage 3'),
    'stage_4':fields.selection([('yes','Yes'),('no','No'),('ineligible','Ineligible')],'d. Stage 4'),
    'HIV_care':fields.selection([('yes','Yes'),('no','No'),('ineligible','Ineligible')],'2. Is the participant followed in an HIV care programme?'),
    'beentoosick':fields.selection([('yes','Yes'),('no','No')],'3. In the last month, has the partcipant been too sick to work or do daily activities?'),
    'days_missed':fields.integer('a. Number of days missed:'),
    'bednetsincevisit':fields.selection([('yes','Yes'),('no','No')],'4. In the past week, has the participant used a bednet?'),
    'ARVssincelastvisit':fields.selection([('yes','Yes'),('no','No')],'5. Since the last visit, has the participant taken any ARVs'),
    'treatment':fields.selection([('yes','Yes'),('no','No')],'a. For Treatment?'),
    'for_pmtct':fields.selection([('yes','Yes'),('no','No')],'b. For PMTCT?'),
    'datestarted':fields.selection([('yes','Yes'),('no','No')],'c. Date when ARV was started'),
    'arvlist':fields.selection([('yes','Yes'),('no','No')],'d. List ARVs taken and then go to item 6:'),
    'not_eligible':fields.selection([('yes','Yes'),('no','No')],'a. not eligible for ARVs'),
    'stigma':fields.selection([('yes','Yes'),('no','No')],'b. Stigma'),
    'feel_heathy':fields.selection([('yes','Yes'),('no','No')],'c. Feeling healthy'),
    'fears':fields.selection([('yes','Yes'),('no','No')],'d. fears/has experienced bad side effects'),
    'notsupportive':fields.selection([('yes','Yes'),('no','No')],'e. clinic was not supportive'),
    'no_slots':fields.selection([('yes','Yes'),('no','No')],'f. no ART slots at the clinic'),
    'said_not_eligible':fields.selection([('yes','Yes'),('no','No')],'g. repeat CD4 count > 350 or clinic said wasnt eligible'),
    'difficult_adherence':fields.selection([('yes','Yes'),('no','No')],'h. adherence was too difficult'),
    'pre-treatment_processing':fields.selection([('yes','Yes'),('no','No')],'i. pre-treatment processing(in queue at ART center)'),
    'transport_cost':fields.selection([('yes','Yes'),('no','No')],'j. transportation costs'),
    'newly_diagnosed':fields.selection([('yes','Yes'),('no','No')],'k. Newly diagnosed'),
    'others':fields.char('l. Others'),
    'co-trimoxazole':fields.selection([('yes','Yes'),('no','No')],'6. Is the participant currently taking co-trimoxazole?'),
    'prophylaxis':fields.boolean('i. Prophylaxis'),
    'pcp_treatment':fields.boolean('ii. PCP treatment'),
    'toxo_treatment':fields.boolean('iii. toxoplasmosis treatment'),
    'otherspecify':fields.boolean('iv.Others (specify)'),
    'isoniazid':fields.selection([('yes','Yes'),('no','No')],"7. Is the participant currently taking isoniazid or another medication as prophylaxis for TB?"),
    'tb_treatment':fields.selection([('yes','Yes'),('no','No')],"8. Is the participant currently being treated for TB?"),
    'participant_pregnant':fields.selection([('yes','Yes'),('no','No')],"9. Female only: Is the participant currently pregnant?"),
    'participant_circumcised':fields.selection([('yes','Yes'),('no','No')],"10. Male only: Since the last visit, has the participant been circumcised?"),
    } 
