from openerp.osv import osv, fields
from openerp import tools

class followupindex_preferquestionnaire(osv.Model):
    _name = "followupindex.preferquestionnaire"
    _columns = {
        'visitdate' : fields.date('Visit Date'),
        'partner_id': fields.many2one('res.partner', 'Sceening ID'),
        'sceening_id': fields.char(string="Sceening ID", related='partner_id.name'),
        'bewilling' : fields.selection([('yes','YES'),('no','NO')],'Would you be willing to start ARVs now if it would lower your chance of giving HIV to your partner?'),
        'noconcerns' : fields.boolean('no concerns'),
        'notwilling' : fields.boolean('not willing to take if there is no benefit for me'),
        'takingARVs' : fields.boolean('taking ARVs means I will die soon'),
        'sideeffects' : fields.boolean('side effects'),
        'pillburden' : fields.boolean('pill burden would be too great for too long'),
        'imaybe' : fields.boolean('I may be forced to disclose'),
        'concernsabout' : fields.boolean('concerns about stigma'),
        'resistancemay' : fields.boolean('resistance may come sooner other'),
        'others' : fields.char('Others'),
        'startonARVs' : fields.boolean('start on ARVs'),
        'havemypartner' : fields.boolean('have my partner use PrEP'),
        'ARVswill' : fields.boolean('ARVs will benefit me in the long term'),
        'mypartner' : fields.boolean('my partner is already used to taking study drug every day'),
        'mypartnercan' : fields.boolean('my partner can take PrEP to show his / her support for me'),
        'ARVsare' : fields.boolean('ARVs are currently free'),
        'ishoulddo' : fields.boolean('I should do everything I can to keep from giving HIV to my partner'),
        'betterfor' : fields.boolean('better for my partner to be in charge of his / her own HIV prevention'),
        'others2' : fields.char('Others'),
        'howmany' : fields.integer('How many more children would you like to have now or in the future?'),
        'currentlytrying' : fields.boolean('currently trying to get pregnant'),
        'currentlypregnant' : fields.boolean('currently pregnant/partner pregnant'),
        'withinthe' : fields.boolean('within the next 2 years'),
        'morethan' : fields.boolean('More than 2 years from now'),
        'Dontknow' : fields.boolean('Dont know'),
        'timedunprotected' : fields.boolean('timed unprotected sex'),
        'takeART' : fields.boolean('take ART'),
        'PrEPfor' : fields.boolean('PrEP for my partner'),
        'others3' : fields.char('Others'),
        'haveyoudiscussed' : fields.selection([('yes','YES'),('no','NO'),('no_current_partner','no current partner')],'Have you discussed your fertility desires with your current partner?'),
        'highrisk' : fields.boolean('High risk'),
        'moderaterisk' : fields.boolean('Moderate risk'),
        'lowrisk' : fields.boolean('Low risk'),
        'norisk' : fields.boolean('No risk'),
        'dontknow2' : fields.boolean('Dont know'),
    } 
