from openerp.osv import osv, fields
from openerp import tools

class followup_saferconception(osv.Model):
    _name = "followup.saferconception"
    _columns = {
        'visit_date':fields.date('Visit Date'),
        'partner_id': fields.many2one('res.partner', 'Sceening ID'),
        'sceening_id': fields.char(string="Sceening ID", related='partner_id.name'),
	    'malecircum':fields.boolean('a. Male circumcision'),
	    'artifiinsem':fields.boolean('b. Artificial insemination'),
	    'spermwash':fields.boolean('c. Sperm washing'),
	    'selfinsem':fields.boolean('d. Self insemination'),
	    'usecondoms':fields.boolean('e. Use condoms except during the most fertile days'),
	    'usePrEP':fields.boolean('f. Use PrEP'),
	    'useARVs':fields.boolean('g. Have my partner use the ARVs'),
	    'treatSTI':fields.boolean('h. Get treatment for STIs'),
	    'commen':fields.boolean('i. Comment'),
	    'none':fields.boolean('j. None'),
	    '2malecircum':fields.boolean('a. Male circumcision'),
	    '2artifiinsem':fields.boolean('b. Artificial insemination'),
	    '2spermwash':fields.boolean('c. Sperm washing'),
	    '2selfinsem':fields.boolean('d. Self insemination'),
	    '2usecondoms':fields.boolean('e. Use condoms except during the most fertile days'),
	    '2usePrEP':fields.boolean('f. Use PrEP'),
	    '2useARVs':fields.boolean('g. Have my partner use the ARVs'),
	    '2treatSTI':fields.boolean('h. Get treatment for STIs'),
	    '2commen':fields.boolean('i. Comment'),
	    '2none':fields.boolean('j. None'),
	    '3malecircum':fields.boolean('a. Male circumcision'),
	    '3artifiinsem':fields.boolean('b. Artificial insemination'),
	    '3spermwash':fields.boolean('c. Sperm washing'),
	    '3selfinsem':fields.boolean('d. Self insemination'),
	    '3usecondoms':fields.boolean('e. Use condoms except during the most fertile days'),
	    '3usePrEP':fields.boolean('f. Use PrEP'),
	    '3useARVs':fields.boolean('g. Have my partner use the ARVs'),
	    '3treatSTI':fields.boolean('h. Get treatment for STIs'),
	    '3commen':fields.boolean('i. Comment'),
	    '3none':fields.boolean('j. None'),
	    '4malecircum':fields.boolean('a. Male circumcision'),
	    '4artifiinsem':fields.boolean('b. Artificial insemination'),
	    '4spermwash':fields.boolean('c. Sperm washing'),
	    '4selfinsem':fields.boolean('d. Self insemination'),
	    '4usecondoms':fields.boolean('e. Use condoms except during the most fertile days'),
	    '4usePrEP':fields.boolean('f. Use PrEP'),
	    '4useARVs':fields.boolean('g. Have my partner use the ARVs'),
	    '4treatSTI':fields.boolean('h. Get treatment for STIs'),
	    '4commen':fields.boolean('i. Comment'),
	    '4none':fields.boolean('j. None'),
	    'babyHIV':fields.selection([('yes','Yes'),('no','No'),('dont_know','Don\'t know')],'5. If a woman has HIV, her baby will always be born with HIV'),
	    'transmit':fields.selection([('yes','Yes'),('no','No'),('dont_know','Don\'t know')],'6. An HIV infected person taking ARVs is less likely to transmit HIV during sex than an infected person not taking ARVs'),
	    'redchances':fields.selection([('yes','Yes'),('no','No'),('dont_know','Don\'t know')],'7. Circumcision reduces the chances that a man can become infected with HIV'),
	    'mancircum':fields.selection([('yes','Yes'),('no','No'),('dont_know','Don\'t know')],'8. If a man is circumcised, the woman cannot become infected with HIV from him'),
	    'fertile':fields.selection([('yes','Yes'),('no','No'),('dont_know','Don\'t know')],'9. A woman is most fertile about 2 weeks after her period.'),
	    'fromsemen':fields.selection([('yes','Yes'),('no','No'),('dont_know','Don\'t know')],"10. Sperm washing is a service offered at some hospitals that can remove HIV from a mans semen so that his partner can become pregnant without getting HIV"),
	    'uninfected':fields.selection([('yes','Yes'),('no','No'),('dont_know','Don\'t know')],'11. An HIV uninfected man with an infected female partner can make her pregnant without putting his penis inside (by inserting semen into her vagina with a needle-less syringe).'),
	    'negative':fields.selection([('yes','Yes'),('no','No'),('dont_know','Don\'t know')],'12. When the partner of an HIV infected person tests negative, the test has made a mistake.'),
	    'withoutcond':fields.selection([('yes','Yes'),('no','No'),('dont_know','Don\'t know')],'13. If an HIV infected man has sex without condoms with an HIV uninfected woman even once, she will definitely become infected with HIV.'),    
    } 
